### PR TITLE
Disable pwhash scryptsalsa

### PR DESCRIPTION
**Pull request by joshjdevl**
Disable salsa and using pwhash() instead #77 

Explicit invoke generateSWIGsource

Invoke submodule-update.sh

Charset UTF-8 #75

### CODE REVIEW

**Comment by kalaspuffar** [comment]
Hi Josh.

I see in this pull request that you tried to turn off the --enable-minimal in the build script and then reverted that change. I want to use scrypt with libsodium-jni so I'm curious about the reasoning. Weren't you able to make it work and want me to take a crack at it or is it a policy change that this library should not support the functions that have been sectioned out as not being a part of the minimal build?

Best regards
Daniel

**Comment by joshjdevl** [comment]
Thank you Daniel. Unfortunately there were unresolved build errors that I was unable to make progress past in #77 . The following was the libsodium owner's [response](https://github.com/jedisct1/libsodium/issues/579#issuecomment-320938295).

Feel free to take a crack at it. If you are able to make progress feel free to submit a pull request.

Thanks!

**Comment by kalaspuffar** [comment]
Hi @joshjdevl 

I'm not sure what you've tried. But I just disabled your update-submodule.sh script and then removed both our --enable-minimal in the gradle file and also removed all --enable-minimal in the libsodium/dist-build directory and the library builds fine for me.

It's a bit sad that we need to depend on the dist-build directory of libsodium when it imposes restrictions in the build process. Maybe this directory should be copied and maintained in libsodium-jni?

Please try this approach so we can see if this is indeed a solution or if the small environment changes I needed to do in order to run the build script made a difference.

Best regards
Daniel

**Comment by joshjdevl** [comment]
Thank you for taking a look. We could remove the --enable-minimal flag in the build.gradle file. 

Regarding removing the --enable-minimal flag in the dist-build directory, one option is to maintain a separate copy of the scripts. Though perhaps another alternative is to make --enable-minimal overridable in libsodium/dist-build/android-build.sh. An overridable flag would be preferred as we wouldn't need to fork libsodium. We could submit a pull request upstream to libsodium.

Any suggestions or convention on how this flag could be handled in the android-build.sh? It's being passed to configure, is there a way to set an environment variable that will disable it? Are you familiar with these type or similar conventions?

**Pull request merged**
