### PR TITLE
Also test using an Android emulator

### PR DESCRIPTION
**Pull request by felixvf**

### CODE REVIEW

**Comment by joshjdevl** [comment]
Thank you for the Android emulator addition. Would it be possible to please resolve the merge conflict and build?

**Comment by felixvf** [comment]
Sorry, it turned out (after issuing this PR) that the Android emulator support was flaky. It sometimes worked and sometimes did not work. My attempts to solve this issue was not complete when this PR was already merged (it just seemed to have been solved, due to the flakyness), so the problem may now have found its way into the master branch. As it seems you are currently working on this, I’ll leave this issue to you until you tell me I should have a look at this.

**Comment by joshjdevl** [comment]
Please if you could submit another pull request from master that would be appreciated. Thanks.

**Comment by joshjdevl** [comment]
Also, I commented out of master for now since it's flaky.

**Pull request merged**
